name: elite_one
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.1.0
  bloc: ^8.1.1
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  intl: ^0.18.0
  line_icons: ^2.0.1
  material_color_utilities: ^0.2.0
  salomon_bottom_bar: ^3.3.2
  slang_flutter: ^3.17.0

dev_dependencies:
  auto_route_generator: ^7.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  slang: ^3.17.0
  very_good_analysis: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/football.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/

flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart
