name: elite_one
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.1.0"

dependencies:
  animated_shimmer: ^1.0.0
  animated_text_kit: ^4.2.2
  auto_route: ^7.1.0
  bloc: ^8.1.1
  cloud_firestore: ^4.7.1
  collection: ^1.17.1
  dio: ^5.1.2
  firebase_analytics: ^10.4.2
  firebase_app_check: ^0.1.4+2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  firebase_performance: ^0.9.2+2
  firebase_remote_config: ^4.2.2
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^5.0.11
  flutter_hicons: ^0.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_polls: ^0.1.2
  flutter_radar_chart: ^0.2.1
  flutter_staggered_grid_view: ^0.6.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  hydrated_bloc: ^9.1.0
  intl: ^0.18.0
  line_icons: ^2.0.1
  material_color_utilities: ^0.2.0
  onesignal_flutter: ^3.5.1
  path_provider: ^2.0.15
  quickalert: ^1.0.1
  salomon_bottom_bar: ^3.3.2
  slang_flutter: ^3.17.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  slang: ^3.17.0
  slang_build_runner: ^3.17.0
  very_good_analysis: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/football.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/animations/

flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart
